### PR TITLE
Have DPD Web App put the searched word into a query parameter

### PR DESCRIPTION
**Pull request by khemarato**
This PR has the https://dpdict.net/  webapp putting the searched term into a "?q=" query param.  It also respects that param when it's there (performing the desired search) and updates the search when the user hits the browser back (or forwards) button.

### CODE REVIEW

**Comment by khemarato** [comment]
This is a very simple implementation and isn't tested.  Please test before merging!

**Review by bdhrs — APPROVED** [review]
Thanks. Tested and works, it also doesn't interefere with other API endpoints which have search queries.

**Comment by thesunshade** [comment]
Thank you both, @khemarato and @bdhrs ! I think this will greatly improve user experience.

Is there an additional build step that has to be run? I'm not seeing the functionality on my device yet, but it's only been 15min. I have done a hard refresh.

**Comment by bdhrs** [comment]
It will become active on Uposatha day when the web server gets updated with the new database.

**Comment by thesunshade** [comment]
Brilliant. 

Thanks!

**Comment by khemarato** [comment]
Thanks, @bdhrs.  Sorry I didn't have WiFi to test it out before sending it over. Looking forward to the update and I hope you have a good Rains! 😁🙏

**Comment by bdhrs** [comment]
@khemarato it all seems to be live and working properly now. thanks for the integration. can you add the website to your OBU digital library?

**Comment by thesunshade** [comment]
It's working for me! Thanks to both of you.

Perhaps a future improvement (as long as it was backwards compatible) would be to encode the url so you don't end up with a mess like this: 

https://www.dpdict.net/?q=anekaj%C4%81tisa%E1%B9%83s%C4%81ra%E1%B9%83

The word could be converted to velthusius, e.g.

https://www.dpdict.net/?q=anekajaatisa.msaara.m

**Comment by bdhrs** [comment]
you mean like the reverse of [this function](https://github.com/digitalpalidictionary/dpd-db/blob/21c211314c7f87b38de123734218078f9ead0eef/exporter/dpd_fastapi/static/home.js#L512)? pull requests accepted ; )

**Comment by thesunshade** [comment]
Yes, That would do it I think. unless Ven @khemarato had another idea.

**Comment by khemarato** [comment]
IDK. Chrome and I believe Safari (?) automatically display these characters "properly":

Screenshot_20240721_145537_Chrome

I'm not particularly excited to replace the browser's built-in urlencoder with a bespoke one that someone will have to maintain in order to make the urls uglier for most users (and prettier for [less than 3% of people](https://www.reddit.com/r/browsers/comments/1169pwl/it_happened_firefox_marketshare_is_now_less_than_3/))

But that's a call I'll leave up to @bdhrs  🙏 😊

**Comment by thesunshade** [comment]
Oh, I wasn't talking about them being ugly when they are in the browser's url bar. They look fine for me there (FF and Chrome). I'm talking about when you give someone the link, as I did in my example post.

Like if I give you this link, can you tell what word it's taking you to?
https://www.dpdict.net/?q=a%C3%B1%C3%B1%C4%81tuk%C4%81ma

**Comment by khemarato** [comment]
Yeah, sorry @thesunshade realized just after hitting post what you meant 😊 Already deleted my comment.  That change sounds reasonable to me. Just do the inverse replaces and then still call urlencode in case the user adds craziness 😊

**Comment by bdhrs** [comment]
@thesunshade @khemarato I'm not convinced that Velthuis "looks better" if that's the goal here. Hex or bad spelling are not the only options. 

What about a simple **share** button that just copies the URL with Unicode diacritics to the clipboard, and lets the browser handle the encoding and decoding? At least then you can read the link like normal Pāḷi text.

**Comment by thesunshade** [comment]
> What about a simple share button that just copies the URL with Unicode diacritics to the clipboard

That is one way to handle it. But actually copying from the url bar is the natural way for people to share a link. Spaces are another thing to consider. Are there ever going to be spaces in the url?

**Pull request merged**
